### ISSUE TITLE
Unable to ensurepip

### ISSUE THREAD

**Issue by extraymond** [snapcrafters/pypy3#6]
Hi! It would be nice to let pypy has permission to host it's own pypi packages.

When try to ensurepip:

```bash
pypy3 -m ensurepip
```

I received:

```
...
OSError: [Errno 30] Read-only file system: '/snap/pypy3/2/site-packages/easy_install.py'
...
```

**Comment by om26er** [comment]
I did look into that briefly, pypy expects to be able to write to $SNAP/site-packages directory which is clearly not allowed to a snap.

The solution would be to find a way to install site-packages in a user writable directory

**Comment by extraymond** [comment]
Is it possible to let pypy find which env its in, and link the lib directory to the env one? I think its still better to isolate pypy with regular python since some packages will be build slightly differently.

For now, it's possible to ensurepip with --user flag, but this will pollute the user directory which might be used by system default python.

**Comment by disconnect3d** [comment]
Bump! It's over a year and `pypy3` is still almost unusable via snap (`--user` is a workaround).

**Comment by Abhisheknarsing** [comment]
try:
pypy3 -m ensurepip --user

**Comment by extraymond** [comment]
Thanks it's working now. Closing this. Thx @Abhisheknarsing
